import { connectToDatabase, closeDatabase } from '../database/connection.js';

const sampleItems = [
  'Wireless Headphones',
  'Laptop Stand',
  'Mechanical Keyboard',
  'USB-C Hub',
  'External Monitor',
  'Webcam',
  'Desk Lamp',
  'Standing Desk',
  'Ergonomic Chair',
  'Mouse Pad',
  'Phone Case',
  'Screen Protector',
  'Power Bank',
  'Cable Organizer',
  'Desk Mat',
  'Blue Light Glasses',
  'Noise Cancelling Earbuds',
  'Smart Watch',
  'Fitness Tracker',
  'Tablet Stand',
  'Wireless Charger',
  'Laptop Sleeve',
  'Backpack',
  'Water Bottle',
  'Coffee Maker',
  'Air Fryer',
  'Blender',
  'Microwave',
  'Toaster',
  'Rice Cooker',
  'Vacuum Cleaner',
  'Robot Vacuum',
  'Air Purifier',
  'Humidifier',
  'Smart Thermostat',
  'Security Camera',
  'Smart Doorbell',
  'Smart Light Bulbs',
  'Smart Plug',
  'Home Assistant',
  'Gaming Console',
  'Gaming Controller',
  'Gaming Mouse',
  'Gaming Keyboard',
  'Gaming Headset',
  'Graphics Card',
  'RAM Upgrade',
  'SSD Drive',
  'External Hard Drive',
  'Printer',
  'Scanner',
  'Projector',
  'Soundbar',
  'Subwoofer',
  'TV Mount',
  'Streaming Device',
  'E-Reader',
  'Tablet',
  'Smartphone',
  'Camera',
  'Tripod',
  'Camera Lens',
  'Camera Bag',
  'Drone',
  'Action Camera',
  'Gimbal',
  'Microphone',
  'Audio Interface',
  'Studio Monitors',
  'MIDI Controller',
  'DJ Controller',
  'Turntable',
  'Record Player',
  'Vinyl Records',
  'Guitar',
  'Bass Guitar',
  'Drum Set',
  'Piano',
  'Keyboard',
  'Synthesizer',
  'Bicycle',
  'Bike Helmet',
  'Bike Lock',
  'Running Shoes',
  'Workout Clothes',
  'Yoga Mat',
  'Dumbbells',
  'Resistance Bands',
  'Foam Roller',
  'Massage Gun',
  'Treadmill',
  'Exercise Bike',
  'Rowing Machine',
  'Elliptical',
  'Pull-up Bar',
  'Bench Press',
  'Barbell Set',
  'Kettlebell',
  'Jump Rope',
  'Boxing Gloves',
  'Punching Bag',
  'Tennis Racket',
  'Tennis Balls',
  'Basketball',
  'Soccer Ball',
  'Football',
  'Baseball Glove',
  'Hockey Stick',
  'Skateboard',
  'Roller Skates',
  'Snowboard',
  'Skis',
  'Surfboard',
  'Snorkel Set',
  'Scuba Gear',
  'Camping Tent',
  'Sleeping Bag',
  'Camping Stove',
  'Cooler',
  'Hiking Backpack',
  'Hiking Boots',
  'Trekking Poles',
  'Headlamp',
  'Flashlight',
  'Multi-tool',
  'Pocket Knife',
  'Compass',
  'GPS Device',
  'Binoculars',
  'Telescope',
  'Microscope',
  'Telescoping Ladder',
  'Tool Set',
  'Drill',
  'Circular Saw',
  'Jigsaw',
  'Sander',
  'Router',
  'Nail Gun',
  'Paint Sprayer',
  'Pressure Washer',
  'Lawn Mower',
  'Leaf Blower',
  'Hedge Trimmer',
  'Chainsaw',
  'Garden Hose',
  'Sprinkler System',
  'Garden Tools',
  'Plant Pots',
  'Soil',
  'Fertilizer',
  'Seeds',
  'Garden Gloves',
  'Knee Pads',
  'Wheelbarrow',
  'Shovel',
  'Rake',
  'Hoe',
  'Trowel',
  'Pruning Shears',
  'Loppers',
  'Garden Fork',
  'Cultivator',
  'Weeder',
  'Garden Cart',
  'Compost Bin',
  'Rain Barrel',
  'Bird Feeder',
  'Bird House',
  'Wind Chimes',
  'Garden Statue',
  'Outdoor Furniture',
  'Patio Set',
  'Hammock',
  'Swing Set',
  'Trampoline',
  'Playground Equipment',
  'Pool',
  'Hot Tub',
  'Pool Cover',
  'Pool Cleaner',
  'Pool Heater',
  'Pool Ladder',
  'Pool Skimmer',
  'Pool Vacuum',
  'Pool Chemicals',
  'Pool Toys',
  'Beach Towels',
  'Beach Umbrella',
  'Beach Chairs',
  'Beach Tent',
  'Cooler Bag',
  'Picnic Basket',
  'Picnic Blanket',
  'Portable Grill',
  'Grill Tools',
  'Grill Cover',
  'Fire Pit',
  'Firewood',
  'Fire Starter',
  'Matches',
  'Lighter',
  'Candles',
  'Candle Holders',
  'Lanterns',
  'String Lights',
  'Solar Lights',
  'Pathway Lights',
  'Spotlights',
  'Security Lights',
  'Motion Sensor Lights',
  'Timer Switch',
  'Smart Switch',
  'Outlet Cover',
  'Extension Cord',
  'Power Strip',
  'Surge Protector',
  'Battery Backup',
  'Generator',
  'Solar Panel',
  'Battery Bank',
  'Inverter',
  'Voltage Converter',
  'Adapter Plug',
  'Travel Adapter',
  'Portable WiFi',
  'VPN Service',
  'Password Manager',
  'Antivirus Software',
  'Cloud Storage',
  'Backup Service',
  'Domain Name',
  'Web Hosting',
  'SSL Certificate',
  'Email Service',
  'CRM Software',
  'Project Management Tool',
  'Time Tracking App',
  'Invoice Software',
  'Accounting Software',
  'Tax Software',
  'Legal Software',
  'Design Software',
  'Video Editing Software',
  'Photo Editing Software',
  'Music Production Software',
  '3D Modeling Software',
  'CAD Software',
  'Code Editor',
  'IDE',
  'Version Control',
  'CI/CD Tool',
  'Monitoring Tool',
  'Analytics Tool',
  'SEO Tool',
  'Marketing Tool',
  'Email Marketing Tool',
  'Social Media Tool',
  'Content Management System',
  'E-commerce Platform',
  'Payment Gateway',
  'Shopping Cart',
  'Inventory Management',
  'Shipping Software',
  'Label Printer',
  'Barcode Scanner',
  'POS System',
  'Cash Register',
  'Credit Card Reader',
  'Receipt Printer',
  'Scale',
  'Label Maker',
  'Stapler',
  'Paper Shredder',
  'File Organizer',
  'Desk Organizer',
  'Pen Holder',
  'Notebook',
  'Planner',
  'Calendar',
  'Whiteboard',
  'Bulletin Board',
  'Cork Board',
  'Magnets',
  'Push Pins',
  'Paper Clips',
  'Binder Clips',
  'Rubber Bands',
  'Tape',
  'Glue',
  'Scissors',
  'Ruler',
  'Measuring Tape',
  'Level',
  'Square',
  'Protractor',
  'Compass',
  'Calculator',
  'Stopwatch',
  'Timer',
  'Alarm Clock',
  'Wake-up Light',
  'Sleep Tracker',
  'Fitness Tracker',
  'Heart Rate Monitor',
  'Blood Pressure Monitor',
  'Thermometer',
  'Scale',
  'Body Fat Scale',
  'Smart Scale',
  'Food Scale',
  'Kitchen Scale',
  'Measuring Cups',
  'Measuring Spoons',
  'Mixing Bowls',
  'Whisk',
  'Spatula',
  'Wooden Spoon',
  'Slotted Spoon',
  'Ladle',
  'Tongs',
  'Serving Spoon',
  'Fork',
  'Knife',
  'Chef Knife',
  'Paring Knife',
  'Bread Knife',
  'Serrated Knife',
  'Boning Knife',
  'Fillet Knife',
  'Cleaver',
  'Knife Block',
  'Knife Sharpener',
  'Cutting Board',
  'Chopping Board',
  'Carving Board',
  'Meat Tenderizer',
  'Meat Mallet',
  'Meat Thermometer',
  'Oven Thermometer',
  'Candy Thermometer',
  'Deep Fry Thermometer',
  'Timer',
  'Kitchen Timer',
  'Oven Mitts',
  'Pot Holders',
  'Apron',
  'Dish Towels',
  'Dish Cloths',
  'Sponges',
  'Scrub Brushes',
  'Dish Soap',
  'Hand Soap',
  'Soap Dispenser',
  'Paper Towels',
  'Napkins',
  'Placemats',
  'Tablecloth',
  'Coasters',
  'Trivets',
  'Salt Shaker',
  'Pepper Mill',
  'Spice Rack',
  'Spice Jars',
  'Spice Labels',
  'Herb Keeper',
  'Garlic Press',
  'Citrus Juicer',
  'Lemon Squeezer',
  'Can Opener',
  'Bottle Opener',
  'Wine Opener',
  'Corkscrew',
  'Ice Cream Scoop',
  'Cookie Scoop',
  'Melon Baller',
  'Apple Corer',
  'Pineapple Corer',
  'Avocado Slicer',
  'Egg Slicer',
  'Egg Separator',
  'Egg Timer',
  'Egg Poacher',
  'Egg Cooker',
  'Hard Boiled Egg Maker',
  'Omelet Pan',
  'Crepe Pan',
  'Waffle Maker',
  'Pancake Griddle',
  'French Press',
  'Pour Over',
  'Espresso Maker',
  'Coffee Grinder',
  'Milk Frother',
  'Tea Kettle',
  'Tea Infuser',
  'Tea Strainer',
  'Tea Set',
  'Mug Warmer',
  'Travel Mug',
  'Insulated Bottle',
  'Water Filter',
  'Water Pitcher',
  'Ice Maker',
  'Ice Tray',
  'Ice Bucket',
  'Wine Cooler',
  'Beer Dispenser',
  'Keg',
  'Growler',
  'Shot Glasses',
  'Cocktail Shaker',
  'Strainer',
  'Muddler',
  'Bar Spoon',
  'Jigger',
  'Pour Spouts',
  'Bottle Pourer',
  'Cocktail Picks',
  'Straws',
  'Stirrers',
  'Coasters',
  'Bar Mat',
  'Bar Tools',
  'Wine Rack',
  'Bottle Opener',
  'Champagne Stopper',
  'Wine Preserver',
  'Decanter',
  'Aerator',
  'Wine Chiller',
  'Beer Glass',
  'Wine Glass',
  'Champagne Flute',
  'Martini Glass',
  'Margarita Glass',
  'Highball Glass',
  'Lowball Glass',
  'Rocks Glass',
  'Collins Glass',
  'Pilsner Glass',
  'Pint Glass',
  'Mug',
  'Stein',
  'Tumbler',
  'Stemware',
  'Crystal',
  'China',
  'Dinnerware',
  'Flatware',
  'Silverware',
  'Chopsticks',
  'Servingware',
  'Platters',
  'Bowls',
  'Salad Bowls',
  'Soup Bowls',
  'Cereal Bowls',
  'Pasta Bowls',
  'Ramekins',
  'Custard Cups',
  'Teacups',
  'Saucers',
  'Plates',
  'Dinner Plates',
  'Salad Plates',
  'Dessert Plates',
  'Bread Plates',
  'Butter Plates',
  'Serving Plates',
  'Cake Stand',
  'Pie Plate',
  'Tart Pan',
  'Quiche Pan',
  'Casserole Dish',
  'Baking Dish',
  'Roasting Pan',
  'Sheet Pan',
  'Cookie Sheet',
  'Pizza Pan',
  'Pizza Stone',
  'Pizza Cutter',
  'Pizza Peel',
  'Baking Mat',
  'Parchment Paper',
  'Wax Paper',
  'Aluminum Foil',
  'Plastic Wrap',
  'Freezer Bags',
  'Storage Bags',
  'Sandwich Bags',
  'Ziploc Bags',
  'Vacuum Sealer',
  'Food Storage Containers',
  'Meal Prep Containers',
  'Lunch Box',
  'Bento Box',
  'Thermos',
  'Insulated Container',
  'Cooler',
  'Ice Pack',
  'Gel Pack',
  'Hot Pack',
  'Heating Pad',
  'Electric Blanket',
  'Weighted Blanket',
  'Throw Blanket',
  'Comforter',
  'Duvet',
  'Duvet Cover',
  'Sheet Set',
  'Fitted Sheet',
  'Flat Sheet',
  'Pillowcases',
  'Pillows',
  'Memory Foam Pillow',
  'Body Pillow',
  'Pregnancy Pillow',
  'Neck Pillow',
  'Travel Pillow',
  'Eye Mask',
  'Ear Plugs',
  'White Noise Machine',
  'Sound Machine',
  'Air Purifier',
  'Humidifier',
  'Dehumidifier',
  'Fan',
  'Ceiling Fan',
  'Table Fan',
  'Tower Fan',
  'Box Fan',
  'Window Fan',
  'Exhaust Fan',
  'Ventilation Fan',
  'Bathroom Fan',
  'Kitchen Exhaust',
  'Range Hood',
  'Microwave Hood',
  'Dishwasher',
  'Garbage Disposal',
  'Trash Compactor',
  'Refrigerator',
  'Freezer',
  'Ice Maker',
  'Water Dispenser',
  'Soda Maker',
  'SodaStream',
  'Juicer',
  'Blender',
  'Food Processor',
  'Stand Mixer',
  'Hand Mixer',
  'Immersion Blender',
  'Stick Blender',
  'Hand Blender',
  'Nutribullet',
  'Vitamix',
  'Magic Bullet',
  'Smoothie Maker',
  'Milkshake Maker',
  'Slushie Maker',
  'Ice Cream Maker',
  'Gelato Maker',
  'Sorbet Maker',
  'Frozen Yogurt Maker',
  'Popsicle Maker',
  'Ice Pop Maker',
  'Ice Cube Tray',
  'Ice Ball Maker',
  'Ice Sphere Maker',
  'Crushed Ice Maker',
  'Ice Shaver',
  'Snow Cone Maker',
  'Shaved Ice Machine',
  'Cotton Candy Maker',
  'Popcorn Maker',
  'Hot Air Popper',
  'Popcorn Machine',
  'Movie Theater Popcorn',
  'Caramel Corn Maker',
  'Kettle Corn Maker',
  'Nacho Maker',
  'Quesadilla Maker',
  'Panini Press',
  'Sandwich Maker',
  'Grilled Cheese Maker',
  'Burger Press',
  'Meat Press',
  'Taco Holder',
  'Taco Shell Rack',
  'Tortilla Press',
  'Tortilla Warmer',
  'Taco Shell Maker',
  'Tostada Maker',
  'Churro Maker',
  'Donut Maker',
  'Donut Pan',
  'Muffin Pan',
  'Cupcake Pan',
  'Cupcake Liners',
  'Cake Pan',
  'Bundt Pan',
  'Tube Pan',
  'Springform Pan',
  'Loaf Pan',
  'Bread Pan',
  'Pullman Pan',
  'Brioche Pan',
  'Baguette Pan',
  'Focaccia Pan',
  'Pizza Pan',
  'Calzone Pan',
  'Empanada Press',
  'Ravioli Maker',
  'Pasta Maker',
  'Pasta Machine',
  'Ravioli Mold',
  'Gnocchi Board',
  'Pasta Drying Rack',
  'Pasta Server',
  'Spaghetti Server',
  'Pasta Fork',
  'Pasta Spoon',
  'Pasta Ladle',
  'Pasta Pot',
  'Stockpot',
  'Saucepan',
  'Frying Pan',
  'Skillet',
  'Sauté Pan',
  'Wok',
  'Dutch Oven',
  'Braiser',
  'Casserole',
  'Tagine',
  'Paella Pan',
  'Risotto Pan',
  'Soufflé Dish',
  'Fondue Pot',
  'Raclette',
  'Hot Pot',
  'Steamer',
  'Bamboo Steamer',
  'Steamer Basket',
  'Steamer Insert',
  'Colander',
  'Strainer',
  'Sieve',
  'Fine Mesh Strainer',
  'Chinois',
  'Food Mill',
  'Ricer',
  'Masher',
  'Potato Masher',
  'Avocado Masher',
  'Banana Masher',
  'Garlic Masher',
  'Onion Chopper',
  'Vegetable Chopper',
  'Food Chopper',
  'Mandoline',
  'Spiralizer',
  'Vegetable Spiralizer',
  'Zoodle Maker',
  'Julienne Peeler',
  'Vegetable Peeler',
  'Apple Peeler',
  'Potato Peeler',
  'Carrot Peeler',
  'Cucumber Peeler',
  'Tomato Peeler',
  'Corn Stripper',
  'Corn Holders',
  'Corn Butterer',
  'Asparagus Peeler',
  'Artichoke Cooker',
  'Artichoke Steamer',
  'Artichoke Server',
  'Lobster Cracker',
  'Lobster Picks',
  'Crab Cracker',
  'Crab Picks',
  'Shrimp Deveiner',
  'Oyster Shucker',
  'Clam Opener',
  'Mussel Opener',
  'Nut Cracker',
  'Nut Picks',
  'Coconut Opener',
  'Coconut Scraper',
  'Pineapple Slicer',
  'Watermelon Slicer',
  'Melon Slicer',
  'Apple Slicer',
  'Apple Corer',
  'Pear Corer',
  'Cherry Pitter',
  'Olive Pitter',
  'Date Pitter',
  'Grapefruit Spoon',
  'Grapefruit Knife',
  'Orange Peeler',
  'Lemon Zester',
  'Citrus Zester',
  'Microplane',
  'Grater',
  'Box Grater',
  'Rotary Grater',
  'Cheese Grater',
  'Parmesan Grater',
  'Nutmeg Grater',
  'Ginger Grater',
  'Wasabi Grater',
  'Horseradish Grater',
  'Truffle Shaver',
  'Chocolate Shaver',
  'Vegetable Brush',
  'Potato Brush',
  'Mushroom Brush',
  'Scrub Brush',
  'Dish Brush',
  'Bottle Brush',
  'Straw Brush',
  'Tub Brush',
  'Toilet Brush',
  'Sponge',
  'Scouring Pad',
  'Steel Wool',
  'Cleaning Cloth',
  'Microfiber Cloth',
  'Dusting Cloth',
  'Polishing Cloth',
  'Glass Cleaner',
  'Multi-surface Cleaner',
  'Disinfectant',
  'Bleach',
  'Vinegar',
  'Baking Soda',
  'Lemon Juice',
  'Essential Oils',
  'Air Freshener',
  'Candle',
  'Wax Melter',
  'Diffuser',
  'Reed Diffuser',
  'Room Spray',
  'Linen Spray',
  'Fabric Refresher',
  'Odor Eliminator',
  'Deodorizer',
  'Charcoal Bags',
  'Baking Soda Boxes',
  'Silica Gel',
  'Moisture Absorber',
  'Damp Rid',
  'Closet Dehumidifier',
  'Shoe Deodorizer',
  'Shoe Freshener',
  'Shoe Inserts',
  'Shoe Trees',
  'Boot Shapers',
  'Shoe Rack',
  'Boot Rack',
  'Shoe Organizer',
  'Shoe Storage',
  'Shoe Boxes',
  'Shoe Bags',
  'Boot Bags',
  'Sneaker Bags',
  'Heel Protectors',
  'Toe Protectors',
  'Sole Protectors',
  'Shoe Covers',
  'Boot Covers',
  'Rain Boots',
  'Snow Boots',
  'Hiking Boots',
  'Work Boots',
  'Safety Boots',
  'Steel Toe Boots',
  'Composite Toe Boots',
  'Waterproof Boots',
  'Insulated Boots',
  'Winter Boots',
  'Fur Lined Boots',
  'Shearling Boots',
  'UGG Boots',
  'Chelsea Boots',
  'Ankle Boots',
  'Knee High Boots',
  'Over The Knee Boots',
  'Cowboy Boots',
  'Riding Boots',
  'Combat Boots',
  'Doc Martens',
  'Timberlands',
  'Hunter Boots',
  'Wellies',
  'Galoshes',
  'Overshoes',
  'Shoe Chains',
  'Ice Cleats',
  'Traction Devices',
  'Crampons',
  'Microspikes',
  'Snowshoes',
  'Skis',
  'Ski Boots',
  'Ski Bindings',
  'Ski Poles',
  'Ski Goggles',
  'Ski Helmet',
  'Ski Gloves',
  'Ski Mittens',
  'Ski Socks',
  'Ski Base Layer',
  'Ski Mid Layer',
  'Ski Jacket',
  'Ski Pants',
  'Ski Bib',
  'Ski Suit',
  'Ski Underwear',
  'Long Underwear',
  'Thermal Underwear',
  'Base Layer',
  'Mid Layer',
  'Insulating Layer',
  'Outer Layer',
  'Shell Jacket',
  'Softshell Jacket',
  'Hard Shell Jacket',
  'Rain Jacket',
  'Windbreaker',
  'Fleece Jacket',
  'Puffer Jacket',
  'Down Jacket',
  'Synthetic Jacket',
  'Wool Jacket',
  'Leather Jacket',
  'Denim Jacket',
  'Bomber Jacket',
  'Track Jacket',
  'Hoodie',
  'Sweatshirt',
  'Sweater',
  'Cardigan',
  'Pullover',
  'V-neck',
  'Crew Neck',
  'Turtleneck',
  'Mock Neck',
  'Henley',
  'Polo Shirt',
  'Button Down',
  'Dress Shirt',
  'Oxford Shirt',
  'Flannel Shirt',
  'Plaid Shirt',
  'Striped Shirt',
  'Solid Shirt',
  'Patterned Shirt',
  'Graphic Tee',
  'Plain Tee',
  'V-neck Tee',
  'Crew Neck Tee',
  'Tank Top',
  'A-shirt',
  'Undershirt',
  'T-shirt',
  'Long Sleeve Tee',
  'Short Sleeve Tee',
  'Sleeveless Tee',
  'Raglan Tee',
  'Baseball Tee',
  'Ringer Tee',
  'Pocket Tee',
  'Vintage Tee',
  'Distressed Tee',
  'Oversized Tee',
  'Fitted Tee',
  'Muscle Tee',
  'Crop Top',
  'Tube Top',
  'Halter Top',
  'Off Shoulder Top',
  'Cold Shoulder Top',
  'One Shoulder Top',
  'Asymmetric Top',
  'Wrap Top',
  'Peplum Top',
  'Blouse',
  'Tunic',
  'Tunic Top',
  'Tunic Dress',
  'Maxi Dress',
  'Midi Dress',
  'Mini Dress',
  'Knee Length Dress',
  'Tea Length Dress',
  'Cocktail Dress',
  'Evening Dress',
  'Formal Dress',
  'Prom Dress',
  'Wedding Dress',
  'Bridal Gown',
  'Bridesmaid Dress',
  'Flower Girl Dress',
  'Pageant Dress',
  'Pageant Gown',
  'Quinceanera Dress',
  'Sweet 16 Dress',
  'Homecoming Dress',
  'Debutante Dress',
  'Ball Gown',
  'A-line Dress',
  'Fit and Flare',
  'Sheath Dress',
  'Bodycon Dress',
  'Shift Dress',
  'Wrap Dress',
  'Shirt Dress',
  'T-shirt Dress',
  'Sweater Dress',
  'Knit Dress',
  'Jersey Dress',
  'Denim Dress',
  'Leather Dress',
  'Lace Dress',
  'Chiffon Dress',
  'Silk Dress',
  'Satin Dress',
  'Velvet Dress',
  'Sequined Dress',
  'Beaded Dress',
  'Embroidered Dress',
  'Printed Dress',
  'Floral Dress',
  'Polka Dot Dress',
  'Striped Dress',
  'Plaid Dress',
  'Gingham Dress',
  'Plaid Skirt',
  'Pleated Skirt',
  'A-line Skirt',
  'Pencil Skirt',
  'Mini Skirt',
  'Midi Skirt',
  'Maxi Skirt',
  'Wrap Skirt',
  'Tiered Skirt',
  'Ruffled Skirt',
  'Tulle Skirt',
  'Tutu',
  'Ballet Skirt',
  'Tennis Skirt',
  'Golf Skirt',
  'Running Skirt',
  'Athletic Skirt',
  'Yoga Skirt',
  'Swim Skirt',
  'Beach Skirt',
  'Sarong',
  'Cover-up',
  'Beach Cover-up',
  'Pool Cover-up',
  'Swim Cover-up',
  'Robe',
  'Bathrobe',
  'Kimono',
  'Yukata',
  'Happi Coat',
  'Haori',
  'Cardigan',
  'Duster',
  'Cape',
  'Poncho',
  'Capelet',
  'Shawl',
  'Wrap',
  'Stole',
  'Pashmina',
  'Scarf',
  'Infinity Scarf',
  'Loop Scarf',
  'Neck Scarf',
  'Bandana',
  'Headscarf',
  'Hijab',
  'Turban',
  'Beanie',
  'Knit Cap',
  'Stocking Cap',
  'Watch Cap',
  'Skull Cap',
  'Balaclava',
  'Face Mask',
  'Neck Gaiter',
  'Buff',
  'Bandana',
  'Headband',
  'Sweatband',
  'Hair Band',
  'Hair Tie',
  'Hair Elastic',
  'Hair Clip',
  'Bobby Pins',
  'Hair Pins',
  'Barrettes',
  'Hair Clips',
  'Hair Claws',
  'Hair Clamps',
  'Hair Forks',
  'Hair Sticks',
  'Chopsticks',
  'Hair Combs',
  'Hair Brushes',
  'Paddle Brush',
  'Round Brush',
  'Vent Brush',
  'Teasing Brush',
  'Boar Bristle Brush',
  'Wide Tooth Comb',
  'Fine Tooth Comb',
  'Rattail Comb',
  'Pick',
  'Afro Pick',
  'Detangling Brush',
  'Wet Brush',
  'Tangle Teezer',
  'Hair Dryer',
  'Blow Dryer',
  'Ionic Hair Dryer',
  'Ceramic Hair Dryer',
  'Tourmaline Hair Dryer',
  'Hair Straightener',
  'Flat Iron',
  'Ceramic Flat Iron',
  'Titanium Flat Iron',
  'Tourmaline Flat Iron',
  'Curling Iron',
  'Curling Wand',
  'Curl Wand',
  'Barrel Curler',
  'Tapered Curler',
  'Spiral Curler',
  'Crimper',
  'Wave Iron',
  'Marcel Iron',
  'Hot Rollers',
  'Curlers',
  'Flexi Rods',
  'Perm Rods',
  'Foam Rollers',
  'Velcro Rollers',
  'Magnetic Rollers',
  'Steam Rollers',
  'Heated Rollers',
  'Self Grip Rollers',
  'Pin Curls',
  'Bobby Pins',
  'Hair Pins',
  'U Pins',
  'Bobby Pins',
  'Kirby Grips',
  'Hair Grips',
  'Hair Clips',
  'Alligator Clips',
  'Duckbill Clips',
  'Sectioning Clips',
  'Hair Clamps',
  'Butterfly Clips',
  'Banana Clips',
  'Octopus Clips',
  'Hair Claws',
  'Hair Forks',
  'Hair Sticks',
  'Chopsticks',
  'Hair Pins',
  'Bobby Pins',
  'Hair Pins',
  'Kirby Grips',
  'Hair Grips',
  'Hair Clips',
  'Barrettes',
  'Hair Clips',
  'Hair Claws',
  'Hair Forks',
  'Hair Sticks',
  'Chopsticks',
  'Hair Combs',
  'Hair Brushes',
  'Paddle Brush',
  'Round Brush',
  'Vent Brush',
  'Teasing Brush',
  'Boar Bristle Brush',
  'Wide Tooth Comb',
  'Fine Tooth Comb',
  'Rattail Comb',
  'Pick',
  'Afro Pick',
  'Detangling Brush',
  'Wet Brush',
  'Tangle Teezer',
  'Hair Dryer',
  'Blow Dryer',
  'Ionic Hair Dryer',
  'Ceramic Hair Dryer',
  'Tourmaline Hair Dryer',
  'Hair Straightener',
  'Flat Iron',
  'Ceramic Flat Iron',
  'Titanium Flat Iron',
  'Tourmaline Flat Iron',
  'Curling Iron',
  'Curling Wand',
  'Curl Wand',
  'Barrel Curler',
  'Tapered Curler',
  'Spiral Curler',
  'Crimper',
  'Wave Iron',
  'Marcel Iron',
  'Hot Rollers',
  'Curlers',
  'Flexi Rods',
  'Perm Rods',
  'Foam Rollers',
  'Velcro Rollers',
  'Magnetic Rollers',
  'Steam Rollers',
  'Heated Rollers',
  'Self Grip Rollers',
  'Pin Curls',
  'Bobby Pins',
  'Hair Pins',
  'U Pins',
  'Bobby Pins',
  'Kirby Grips',
  'Hair Grips',
  'Hair Clips',
  'Alligator Clips',
  'Duckbill Clips',
  'Sectioning Clips',
  'Hair Clamps',
  'Butterfly Clips',
  'Banana Clips',
  'Octopus Clips',
  'Hair Claws',
  'Hair Forks',
  'Hair Sticks',
  'Chopsticks',
  'Hair Pins',
  'Bobby Pins',
  'Hair Pins',
  'Kirby Grips',
  'Hair Grips',
  'Hair Clips',
  'Barrettes',
  'Hair Clips',
  'Hair Claws',
  'Hair Forks',
  'Hair Sticks',
  'Chopsticks',
  'Hair Combs',
  'Hair Brushes',
  'Paddle Brush',
  'Round Brush',
  'Vent Brush',
  'Teasing Brush',
  'Boar Bristle Brush',
  'Wide Tooth Comb',
  'Fine Tooth Comb',
  'Rattail Comb',
  'Pick',
  'Afro Pick',
  'Detangling Brush',
  'Wet Brush',
  'Tangle Teezer',
];

const sampleCategories = [
  'Electronics',
  'Clothing',
  'Home & Kitchen',
  'Sports & Outdoors',
  'Books',
  'Toys & Games',
  'Beauty & Personal Care',
  'Health & Fitness',
  'Automotive',
  'Tools & Home Improvement',
  'Garden & Outdoor',
  'Pet Supplies',
  'Baby Products',
  'Office Supplies',
  'Musical Instruments',
];

const statuses = ['considering', 'want', 'bought', 'archived'];
const priorities = [1, 2, 3, 4, 5];

function getRandomElement(array) {
  return array[Math.floor(Math.random() * array.length)];
}

function getRandomPrice() {
  return Math.round((Math.random() * 1000 + 10) * 100) / 100;
}

function getRandomDate(start, end) {
  return new Date(
    start.getTime() + Math.random() * (end.getTime() - start.getTime())
  );
}

async function seedDatabase() {
  try {
    const db = await connectToDatabase();

    await db.collection('items').deleteMany({});
    await db.collection('categories').deleteMany({});

    console.log('Creating categories...');
    const categoryDocs = sampleCategories.map((name) => ({
      name,
      description: `Items related to ${name.toLowerCase()}`,
      createdAt: new Date(),
      updatedAt: new Date(),
    }));

    const categoryResult = await db.collection('categories').insertMany(categoryDocs);
    const categoryIds = Object.values(categoryResult.insertedIds);

    console.log('Creating items...');
    const itemDocs = [];
    const startDate = new Date(2023, 0, 1);
    const endDate = new Date();

    for (let i = 0; i < 1200; i++) {
      const item = {
        title: sampleItems[i % sampleItems.length] + (i > sampleItems.length ? ` ${Math.floor(i / sampleItems.length)}` : ''),
        link: Math.random() > 0.3 ? `https://example.com/product/${i}` : null,
        price: Math.random() > 0.4 ? getRandomPrice() : null,
        priority: getRandomElement(priorities),
        status: getRandomElement(statuses),
        categoryId: Math.random() > 0.2 ? getRandomElement(categoryIds).toString() : null,
        notes: Math.random() > 0.6 ? `Notes for item ${i + 1}` : null,
        createdAt: getRandomDate(startDate, endDate),
        updatedAt: getRandomDate(startDate, endDate),
      };
      itemDocs.push(item);
    }

    for (let i = 0; i < itemDocs.length; i += 100) {
      const batch = itemDocs.slice(i, i + 100);
      await db.collection('items').insertMany(batch);
      console.log(`Inserted ${Math.min(i + 100, itemDocs.length)} items...`);
    }

    const itemCount = await db.collection('items').countDocuments();
    const categoryCount = await db.collection('categories').countDocuments();

    console.log(`\n✅ Database seeded successfully!`);
    console.log(`   Items: ${itemCount}`);
    console.log(`   Categories: ${categoryCount}`);

    await closeDatabase();
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    await closeDatabase();
    process.exit(1);
  }
}

seedDatabase();
